# Docker file only for development
# Custom Docker file must be run as 'docker build -f Dockerfile.dev .'
FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

COPY . .

CMD ["npm", "run", "start"]
