version: "3"
services:
  react-app:
    build: # build with custom file
      context: . # the same folder where docker-compose is
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes: # -v flag with docker build
      - /app/node_modules
      - .:/app # from '.' to (:) '/app'
  react-test:
    build: # build with custom file
      context: . # the same folder where docker-compose is
      dockerfile: Dockerfile.dev
    volumes: # -v flag with docker build
      - /app/node_modules
      - .:/app # from '.' to (:) '/app'
    command: ["npm", "run", "test"]
